namespace Classe_Editor.ClasseData {
    public class StatsBase {
        public object HP { get; set; }
        public object MP { get; set; }
        public object SP { get; set; }
        public object RegenHP { get; set; }
        public object RegenMP { get; set; }
        public object RegenSP { get; set; }
        public object Level { get; set; }
        public object Strenght { get; set; }
        public object Dexterity { get; set; }
        public object Agility { get; set; }
        public object Constitution { get; set; }
        public object Intelligence { get; set; }
        public object Wisdom { get; set; }
        public object Will { get; set; }
        public object Mind { get; set; }
        public object Charisma { get; set; }
        public object Points { get; set; }
        public object DamageSuppression { get; set; }
        public object Enmity { get; set; }
        public object AdditionalDamage { get; set; }
        public object HealingPower { get; set; }
        public object Concentration { get; set; }
        public object AttackSpeed { get; set; }
        public object CastSpeed { get; set; }
        public object Attack { get; set; }
        public object Accuracy { get; set; }
        public object Defense { get; set; }
        public object Evasion { get; set; }
        public object Block { get; set; }
        public object Parry { get; set; }
        public object CriticalRate { get; set; }
        public object CriticalDamage { get; set; }
        public object MagicAttack { get; set; }
        public object MagicAccuracy { get; set; }
        public object MagicDefense { get; set; }
        public object MagicResist { get; set; }
        public object MagicCriticalRate { get; set; }
        public object MagicCriticalDamage { get; set; }
        public object AttributeFire { get; set; }
        public object AttributeWater { get; set; }
        public object AttributeEarth { get; set; }
        public object AttributeWind { get; set; }
        public object AttributeLight { get; set; }
        public object AttributeDark { get; set; }
        public object ResistStun { get; set; }
        public object ResistParalysis { get; set; }
        public object ResistSilence { get; set; }
        public object ResistBlind { get; set; }
        public object ResistCriticalRate { get; set; }
        public object ResistCriticalDamage { get; set; }
        public object ResistMagicCriticalRate { get; set; }
        public object ResistMagicCriticalDamage { get; set; }
    }
}
